# Sync repo to the Codeberg mirror
name: codeber-mirror
on:
  push:
    branches:
    - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://codeberg.org/IamDg/LibreFit.git'
            GIT_USERNAME: IamDg
            GIT_PASSWORD: ${{ YTRwo3NryRvQEdCRHojsPWzmz17ahZ6Z8ua7TmlT }}
